version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    image: postgres:latest
    container_name: ripple_sync_postgres
    command: postgres -c shared_preload_libraries=pg_cron -c cron.database_name=ripple_sync
    environment:
      POSTGRES_USER: JukmanDev
      POSTGRES_PASSWORD: Juk20Man25
      POSTGRES_DB: ripple_sync
    ports:
      - "50003:5432"
    volumes:
      - postgres_ripplesync_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U JukmanDev -d ripple_sync"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_ripplesync_data: